# Generated by Django 4.0 on 2021-12-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QrcodeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=256)),
                ('qrcode_img', models.ImageField(blank=True, null=True, upload_to='qrcode')),
            ],
        ),
    ]
